### ISSUE TITLE
Error on Lubuntu 21.10 upon signing in (Also happens on built in "simple" theme for nody-greeter)

### ISSUE THREAD

**Issue by ro1y** [mshernandez5/WelcomeXP#10]
Upon signing in and the welcome message appearing, an error shows up and I cannot log in.
![20220115_232348](https://user-images.githubusercontent.com/76408418/149672277-4c3b0be3-221e-4c7f-a02b-275c05455418.jpg)

**Comment by mshernandez5** [comment]
If this happens with the built-in nody-greeter themes as well then you should post an issue [here](https://github.com/JezerM/nody-greeter/issues) at the greeter repository.

I am short on time at the moment but soon I will see if I can reproduce this on a clean Lubuntu install.

For the time being you can switch to another TTY (ex. by using `CTRL + ALT + F6`) and switch back to your previous greeter. You should be able to switch back to SDDM (the Lubuntu default) with `sudo dpkg-reconfigure sddm`. If you were using another lightdm greeter previously, you can use the `vim` or `nano` editors to revert the `greeter-session=nody-greeter` change in your lightdm configuration.

**Comment by mshernandez5** [comment]
I got some time and was able to reproduce the issue on a clean install of Lubuntu.
The issue seems to be that the default user session is not set, which causes problems for themes like this one which rely on the default.

Add `user-session=Lubuntu` to your lightdm configuration and that should do the trick:
```
[SeatDefaults]
user-session=Lubuntu
greeter-session=nody-greeter
```
