### ISSUE TITLE
How to install WelcomeXP?

### ISSUE THREAD

**Issue by Santarina** [mshernandez5/WelcomeXP#7]
Hi, I'm very new to Linux. How to install WelcomeXP into Linux Mint? I'm totally clueless when I saw your Installation instruction in your web site. Thanks.

**Comment by mshernandez5** [comment]
The instructions give a good amount of detail but can't provide small steps for everything because these can differ between distributions. If you are having a hard time reading the instructions then this might be risky to do, just be aware that an error here could prevent you from logging in. If you'd like to continue, here are some specific steps to complete some of the instructions on Linux Mint:

The first step is installing and enabling `lightdm-webkit2-greeter`; this is necessary to use HTML/CSS/JS themes like this one. Unfortunately I believe this package has not been in active development since the project maintaining it (Antergos) has fallen apart, be aware that it may break at some point as everything around this package gets updated.

You can still find one of the older `.deb` installers [here](https://download.opensuse.org/repositories/home:/antergos/xUbuntu_17.10/amd64/lightdm-webkit2-greeter_2.2.5-1+15.31_amd64.deb) at OpenSuse software.

To enable the webkit greeter on Linux Mint, you can create a new configuration file using `sudo nano /etc/lightdm/lightdm.conf.d/webkitgreeter.conf` with these contents:
```
[SeatDefaults]
greeter-session=lightdm-webkit2-greeter
```

To exit and save from the terminal text editor, use `CTRL+X` (to exit), `Y` (yes, want to save), then just `ENTER` without modifying the file path.

Don't worry about step 3.

Steps 4, 5, and 6 are pretty straightforward and already give any commands you'd need.

The configuration you need to edit for step 7 is `/etc/lightdm/lightdm-webkit2-greeter.conf`.
You can use the `nano` editor in the terminal for this as well.

That is pretty much it, you can run the test mode in step 9 just to be careful and make sure you haven't lost the ability to login before restarting or logging out. All you are looking for when running this is a small window with the XP login screen and no error messages, don't click anything inside the window or do anything with it. If you see this things are good, you can just close the window and the login screen should be good to go.

**Comment by Santarina** [comment]
Hi,
I already test it and it working fine. :) Thanks. Is there anyway change Lock Screen too?

**Comment by mshernandez5** [comment]
> Hi, I already test it and it working fine. :) Thanks. Is there anyway change Lock Screen too?

No problem, glad it's working for you!
There is no lock screen unfortunately, just the login screen.
I might look into this in the future but am busy with other projects at the moment.
